### PR TITLE
Refactored to work with Truffle 3.3.0

### PR DESCRIPTION
**Pull request by mdance**
Hey, I am experimenting with your drupal ethereum functionality and I have refactored it to work with the latest truffle webpack format.

### CODE REVIEW

**Comment by digitaldonkey** [comment]
An update sounds cool.

Currently I'm working on a similar functionality using EcVerify. It will be free to sign-up then, because no more contract required. (But also no payed registration). 

As far as I can see you didn't change the contract itself. The "Test-environment" really needs an update and I would love to merge. 

But testing your commits (https://github.com/mdance/register_drupal_ethereum.git) I get an error: 
(Truffle v3.4.3). Any suggestions?

```
Error: Cannot find module 'truffle-default-builder'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/register_drupal_ethereum/truffle.js:1:84)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by mdance** [comment]
I had to do a npm install truffle-default-builder in order to get truffle compile to work.  I think its due to the node_modules being in .gitignore

**Comment by digitaldonkey** [comment]
I can't get it to work:

```
git pull https://github.com/mdance/register_drupal_ethereum.git truffle-3-3-0
npm i
truffle migrate
 truffle serve
Serving static assets in ./build on port 8080...
/Users/tho/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/cli.bundled.js:124978
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/Users/tho/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/cli.bundled.js:124978:11)
    at setFSEventsListener (/Users/tho/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/cli.bundled.js:125032:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/Users/tho/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/cli.bundled.js:125196:16)
    at FSWatcher.<anonymous> (/Users/tho/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/cli.bundled.js:125330:25)
    at LOOP (fs.js:1718:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

My environment:
```
truffle -v
Truffle v3.4.3 - a development framework for Ethereum
npm -v
4.2.0
node -v
v7.8.0
```

Any idea?

**Comment by mdance** [comment]
Try running:
npm install truffle-default-builder

The new command to run the web server is:

npm run dev

**Comment by digitaldonkey** [comment]
> npm run dev

Helps. But still a lot of errors (static files not found) 
And I can't get it working.

**Comment by digitaldonkey** [comment]
I'll check back on this as soon as I find the time.
